template:
  path: opensearch.yaml
  type: file
parameters:
  OpenSearchUsername: {{ var.opensearchuser }}
  OpenSearchPassword: {{ var.opensearchpw }}
  OpenSearchSubnet1: !stack_output beckstep1/subnets.yaml::PrivateSubnet1
  OpenSearchSubnet2: !stack_output beckstep1/subnets.yaml::PrivateSubnet2
  OpenSearchSubnet3: !stack_output beckstep1/subnets.yaml::PrivateSubnet3
