template:
  path: us-east-1/subnets.yaml
  type: file
parameters:
  MyVPCId: !stack_output es-leader-crossaccount/vpc.yaml::VpcId
  CidrBlockSubPriv1: 10.3.0.0/24
  CidrBlockSubPriv2: 10.3.2.0/24
  CidrBlockSubPriv3: 10.3.4.0/24
  OtherRegionCidrBlock: 10.2.0.0/20
  