template:
  path: crossclustercr.yaml
  type: file
parameters:
  ConnectionAlias: {{ var.opensearchconnalias }}
  CRLambda: !stack_output es-follower/crossaccountlambda.yaml::CrossClusterSetupArn
  LocalDomain: !stack_output es-follower/opensearch.yaml::OpenSearchDomainName
  RemoteAccount: !stack_output es-leader-crossaccount/opensearch.yaml::OpenSearchAccount
  RemoteDomain: !stack_output es-leader-crossaccount/opensearch.yaml::OpenSearchDomainName
  RemoteRegion: !stack_output es-leader-crossaccount/opensearch.yaml::OpenSearchRegion