template:
  path: opensearch.yaml
  type: file
parameters:
  OpenSearchUsername: 'admin'
  OpenSearchPassword: 'L3tM31nN0w!'
  OpenSearchSubnet1: !stack_output es-leader/subnets.yaml::PrivateSubnet1
  OpenSearchSubnet2: !stack_output es-leader/subnets.yaml::PrivateSubnet2
  OpenSearchSubnet3: !stack_output es-leader/subnets.yaml::PrivateSubnet3